import { Question, QuestionType } from './types.ts';

export const ALL_QUESTIONS: Question[] = [
  {
    id: 'age',
    section: 'adult',
    type: QuestionType.SingleChoice,
    text: '1. Koliko imate godina?',
    options: ['18–24', '25–34', '35–44', '45–55', '55+'],
  },
  {
    id: 'gender',
    section: 'adult',
    type: QuestionType.SingleChoice,
    text: '2. Spol:',
    options: ['Muško', 'Žensko', 'Ne želim odgovoriti'],
  },
  {
    id: 'lifestyle',
    section: 'adult',
    type: QuestionType.MultipleChoice,
    text: '3. Kako biste opisali svoj stil života?',
    options: [
      'Bavim se planinarenjem / trekkingom / aktivnim sportom',
      'Vježbam 1–3× tjedno',
      'Uglavnom sjedilački način života',
      'Pravilno se hranim i/ili pratim nutritivne smjernice',
      'Tražim praktične užine za posao / školu',
    ],
  },
  {
    id: 'snack_frequency',
    section: 'adult',
    type: QuestionType.SingleChoice,
    text: '4. Koliko često koristite užinu/snack između glavnih obroka?',
    options: [
      'Nikad',
      'Rijetko (manje od 1× tjedno)',
      'Povremeno (1–3× tjedno)',
      'Često (4–6× tjedno)',
      'Vrlo često (svaki dan)',
    ],
  },
  {
    id: 'criteria_importance',
    section: 'adult',
    type: QuestionType.RatingScale,
    text: '5. Kada birate užinu, koliko su vam sljedeći kriteriji važni?',
    criteria: [
      'Zdravstveni benefiti (npr. nutritivna vrijednost)',
      'Okus / zadovoljstvo',
      'Praktičnost / lako ponijeti',
      'Lokalna proizvodnja / domaći proizvod',
      'Cijena',
      'Ekološko / održivo pakiranje',
    ],
  },
  {
    id: 'tried_kaki',
    section: 'adult',
    type: QuestionType.SingleChoice,
    text: '6. Da li ste ikada probali kaki (japansku jabuku) / sušeni kaki?',
    options: [
      'Da, često',
      'Da, jednom ili par puta',
      'Ne, nikada ali znam što je',
      'Ne, nikada i ne znam što je',
    ],
  },
  {
    id: 'tried_cupter',
    section: 'adult',
    type: QuestionType.SingleChoice,
    text: '7. Da li ste ikada probali ćupter?',
    options: [
      'Da, često',
      'Da, jednom ili par puta',
      'Ne, nikada ali znam što je',
      'Ne, nikada i ne znam što je',
    ],
  },
  {
    id: 'interest_level',
    section: 'adult',
    type: QuestionType.SingleChoice,
    text: '8. Ako biste imali priliku probati sušeni kaki / ćupter iz BiH (brend Kaori), koliko biste bili zainteresirani?',
    options: [
      '1 - Nikako zainteresiran(a)',
      '2',
      '3',
      '4',
      '5 - Odmah bih kupio/la',
    ],
  },
  {
    id: 'price_acceptability',
    section: 'adult',
    type: QuestionType.SingleChoice,
    text: '9. Koju cijenu biste smatrali prihvatljivom za pakiranje (npr. 80-100 g) sušenog kakija / ćuptera kao pravilne užine?',
    options: ['Do 5 KM', '5–7 KM', '7–10 KM', 'Više od 10 KM'],
  },
  {
    id: 'motivation',
    section: 'adult',
    type: QuestionType.MultipleChoice,
    maxChoices: 2,
    text: '10. Što bi vas najviše motiviralo da kupite ovaj proizvod? (odaberite 1–2)',
    options: [
      'Zdravstveni benefiti (npr. više vlakana, antioksidansi)',
      'Praktičnost (možeš ponijeti u planinarenje/posao)',
      'Domaći brend / plod Bosne i Hercegovine',
      'Poseban ukus / novitet (nisam ranije jeo/la)',
      'Pakiranje koje je ekološki prihvatljivo',
      'Bez ulja',
    ],
  },
  {
    id: 'natural_variation',
    section: 'adult',
    type: QuestionType.SingleChoice,
    text: '11. Bi li vam smetale razlike u boji i veličini komadića (čipsa) koje nastaju prirodnim sušenjem proizvoda?',
    options: [
      'Ne, to mi je sasvim u redu (prirodan proizvod)',
      'Ne, ako je okus dobar',
      'Možda, ovisi o izgledu',
      'Da, volio/la bih da su komadići ujednačeni',
    ],
  },
  {
    id: 'has_children',
    section: 'adult',
    type: QuestionType.SingleChoice,
    text: '12. Imate li djecu?',
    options: ['Da', 'Ne'],
  },
  {
    id: 'child_age',
    section: 'parents',
    type: QuestionType.SingleChoice,
    text: '13. Koliko godina ima vaše dijete (ili najstarije dijete)?',
    options: ['< 5 godina', '6–9 godina', '10–13 godina', '14–17 godina', '18+'],
  },
  {
    id: 'parent_criteria_importance',
    section: 'parents',
    type: QuestionType.RatingScale,
    text: '14. Koliko vam je važno da užine koje dijete jede budu:',
    criteria: [
      'Prirodne, bez aditiva',
      'Pravilne (npr. bogate vlaknima, vitaminima)',
      'Domaće, lokalne proizvodnje',
      'Ukusne i privlačne djeci',
      'Lako dostupne i praktične za školu',
    ],
  },
  {
    id: 'allow_child_snack',
    section: 'parents',
    type: QuestionType.SingleChoice,
    text: '15. Biste li dopustili da vaše dijete jede sušeni kaki / ćupter kao pravilnu užinu?',
    options: [
      'Da, svakako',
      'Da, ako je bez dodanog šećera',
      'Možda, ovisi o okusu i cijeni',
      'Nisam siguran/na, trebam više informacija',
      'Ne bih',
    ],
  },
  {
    id: 'parent_motivation',
    section: 'parents',
    type: QuestionType.MultipleChoice,
    text: '16. Što bi vas najviše potaknulo da djetetu ponudite takav proizvod?',
    options: [
      'Znanje da je proizvod pravilan i prirodan',
      'Bez dodanog šećera',
      'Domaći proizvod iz BiH',
      'Preporuka nutricionista ili škole',
      'Zabavno i privlačno pakiranje za djecu',
      'Bez ulja',
    ],
  },
  {
    id: 'purchase_location',
    section: 'parents',
    type: QuestionType.SingleChoice,
    text: '17. Gdje biste najradije kupovali takvu pravilnu užinu za djecu?',
    options: [
      'U supermarketu',
      'U lokalnoj trgovini / na pijaci',
      'Online',
      'U školskoj kantini / automatu',
    ],
  },
  {
    id: 'child_price_acceptability',
    section: 'parents',
    type: QuestionType.SingleChoice,
    text: '18. Koliko biste bili spremni platiti pakiranje (80-100 g) sušenog kakija / ćuptera za dijete?',
    options: ['Do 5 KM', '5–7 KM', '7–10 KM', 'Više od 10 KM'],
  },
  {
    id: 'parent_feedback',
    section: 'parents',
    type: QuestionType.OpenEnded,
    text: '19. Ako imate komentar ili prijedlog – što biste željeli vidjeti kod pravilne užine za djecu (okus, pakiranje, količina, dodatci…)?',
    isOptional: true,
  },
];